# Problem statement 1

In [ ]:
""" Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and 
create a real matrix product.
"""

In [2]:
# importing numpy library
import numpy as np


In [7]:
def MatrixMultiplication(M, N, A):
    """"
    This program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and 
create a real matrix product
"""
    # creating a M x N matrix
    matrix1 = np.random.random(size=(M, N))
    print("First array: \n", matrix1)
    print('\n')

    # creating a N x A matrix
    matrix2 = np.random.random(size=(N, A))
    print("Secondary array: \n", matrix2)
    print('\n')

    # matrix multiplication
 
    matrix3 = np.dot(matrix1, matrix2)
    print("dot product of the two arrays: \n", matrix3)
    print('\n')


# calling the function

MatrixMultiplication(5, 3, 2)

First array: 
 [[0.77359898 0.97649205 0.23327784]
 [0.64105887 0.15591668 0.83287165]
 [0.81402012 0.98604184 0.99039928]
 [0.99883066 0.23938577 0.79299229]
 [0.27487269 0.06878074 0.8387945 ]]


Secondary array: 
 [[0.33200886 0.13549993]
 [0.01243632 0.86823488]
 [0.39412822 0.09662319]]


dot product of the two arrays: 
 [[0.36092707 0.97518712]
 [0.54303448 0.30271045]
 [0.67286894 1.06211113]
 [0.64713835 0.419806  ]
 [0.42270813 0.17801007]]




# Problem statement 2

In [8]:
"""Problem Statement 2: Write a NumPy program to check if each element of an array of your 
choice is composed of digits, lower case letters, and upper case letters only."""

'Problem Statement 2: Write a NumPy program to check if each element of an array of your \nchoice is composed of digits, lower case letters, and upper case letters only.'

In [77]:
def check_array(array):
    """This function is to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only."""
    Digit_Only = []
    Lower_Case_Only = []
    Upper_Case_Only = []
    # iterating each element in the array
    
    for i in array:
        # checking if each element is composed of digits, lower case letters, and upper case letters only
        if i.isdigit():
            Digit_Only.append(True)
           
        else:
            Digit_Only.append(False)

        

        if i.islower():
            Lower_Case_Only.append(True)
        else:
            Lower_Case_Only.append(False)

        if i.isupper():
            Upper_Case_Only.append(True)
        else:
            Upper_Case_Only.append(False)

       # returning the result with new line character


    return  "Digit only = {}\nLower case only = {}\nUpper case only = {}.".format(Digit_Only, Lower_Case_Only, Upper_Case_Only)


Array = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'])

check_array(Array)

'Digit only = [False, False, False, False, False, True]\nLower case only = [False, False, False, False, True, False]\nUpper case only = [False, True, True, False, False, False].'

# Problem statement 3

In [44]:
"""Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and 
𝑌 as input and perform the following tasks:
"""

'Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and \n𝑌 as input and perform the following tasks:\n'

In [67]:
def input_function():
    """This function is to read two space-separated positive integers 𝑋 and Y as input"""

    # Step 1: Read input values X and Y
    X, Y = map(int, input("Enter two space-separated positive integers X and Y: ").split())


    # 2.1. Create a list (lst1) starting at one (1) with 16 elements at a step of X

    lst1 =list(range(1, X * 16 +1 ,X))

    # 2.2. Create a list (lst2) starting at one (1) with 16 elements at a step of Y

    lst2 =list(range(1,Y * 16 +1 ,Y))

    # 3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

    np1 = np.array(lst1)

    np2 = np.array(lst2)

    #4. # Reshape both the NumPy arrays to (4,4

    np1 = np1.reshape(4,4)

    np2 = np2.reshape(4,4)

    # 5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 - np2)

    np3 = np1 - np2

    # Print all the elements of np3 in a single dimension
    return np3.flatten()


# calling the function

input_function()


array([  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20, -22, -24,
       -26, -28, -30])

In [59]:
# 1. Create a list (lst1) starting at one (1) with 16 elements at a step of X

lst1 =list(range(0,32,2))


# 2. Create a list (lst2) starting at one (1) with 16 elements at a step of Y

lst2 =list(range(0,47,3))

len(lst2)

16

In [66]:
# 3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

np1 = np.array(lst1)

np2 = np.array(lst2)

np1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [61]:
# Reshape both the NumPy arrays to (4,4

np1 = np1.reshape(4,4)

np2 = np2.reshape(4,4)


In [62]:
# 5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 - np2)

np3 = np1 - np2

print(np3)




[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


In [64]:
# 6. Print all the elements of np3 in a single dimension

np3.flatten()

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15])

In [34]:
"""Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of 
shape [3 ∗ 3] and perform the following task:

Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄)


"""

'Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of \nshape [3 ∗ 3] and perform the following task:\n\nPrint the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄)\n\n\n'

In [42]:
def element_wise_difference(P: 'array', Q: array) -> array:
    """
    This function takes two integer-NumPy arrays, 𝑃 and 𝑄 of shape [3 ∗ 3] and perform the following task: 

    Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄)

    """
    matrix_1 = P.reshape(3, 3)

    matrix_2 = Q.reshape(3, 3)
   
    return matrix_1 - matrix_2

# calling the function

element_wise_difference(np.array([23, 56 ,87, 3 ,6 ,96 ,4 ,6 ,78]), np.array([12 ,34, 54, 7 ,2 ,54, 6, 2, 78]))

array([[11, 22, 33],
       [-4,  4, 42],
       [-2,  4,  0]])